### PR TITLE
Fix 403 authorization errors

### PR DESCRIPTION
**Pull request by Teuns**
Probably related: #127 

For some reason the authentication process returns 403 errors all of a sudden. I think this is due to CloudFlare blocking the requests automatically. This branch solves it by using `urllib` instead of `requests` in the specific faulty requests, as pointed out in a StackOverflow post](https://stackoverflow.com/a/74674276).

### CODE REVIEW

File: kobodl/kobo.py [hunk 1]
```diff
@@ -496,4 +526,19 @@ def Login(self, email: str, password: str, captcha: str) -> None:
         ]  # We don't call self.Settings.Save here, AuthenticateDevice will do that if it succeeds.
         userKey = parsedQueries["userKey"][0]
 
+        cookie = SimpleCookie()
+        cookie.load(authCookie)
+
+        def get_cookie_value(cookie_name):
+            if cookie_name in cookie:
+                return cookie[cookie_name].value
+            return None
```
Comment (lubomir-brindza) [inline kobodl/kobo.py:535]: This closure is never called; did you mean to leave this in here?

**Comment by lubomir-brindza** [comment]
I can confirm that this PR does fix the issue for me, nice work :)

File: kobodl/kobo.py [hunk 2]
```diff
@@ -166,7 +184,7 @@ def __GetExtraLoginParameters(self) -> Tuple[str, str, str]:
             )
         requestVerificationToken = html.unescape(match.group(1))
 
-        return koboSignInUrl, workflowId, requestVerificationToken
+        return koboSignInUrl, workflowId, requestVerificationToken, authCookie
```
Comment (lubomir-brindza) [inline kobodl/kobo.py:187]: Don't forget to update the return type for `__GetExtraLoginParameters`  to `Tuple[str, str, str, str]`

File: kobodl/kobo.py (hunk 1 above)
Comment (Teuns) [reply kobodl/kobo.py:535]: Nice catch! That definitely shouldn't be in here. I'll delete it

**Comment by subdavis** [comment]
Thanks everyone for your involvement in this fix. I'll get this merged and released later this evening.

**Comment by rainrdx** [comment]
> This doesn't seem to fix it for me, but I'm seeing it on the download request.
> 
> ```
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storedownloads.kobo.com/download?downloadToken=XXXXXXXX
> ```

Seems to still get 403 Forbidden on my end sadly

**Comment by Teuns** [comment]
> > This doesn't seem to fix it for me, but I'm seeing it on the download request.
> > ```
> > requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storedownloads.kobo.com/download?downloadToken=XXXXXXXX
> > ```
> 
> Seems to still get 403 Forbidden on my end sadly

Hmm, strange. I suppose it could be fixed by replacing that request with `urllib` too. I'll take a look at it. What OS are you running it on?

**Comment by rainrdx** [comment]
> > > This doesn't seem to fix it for me, but I'm seeing it on the download request.
> > > ```
> > > requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storedownloads.kobo.com/download?downloadToken=XXXXXXXX
> > > ```
> > 
> > 
> > Seems to still get 403 Forbidden on my end sadly
> 
> Hmm, strange. I suppose it could be fixed by replacing that request with `urllib` too. I'll take a look at it. What OS are you running it on?

I’m running it on macOS but I’m on vacation so I’m from weird IP. Maybe it’s IP related and I will try again once I’m back home with residential IP in the U.S.

**Comment by chewi** [comment]
Gentoo here, running at home in Scotland on a static IP. I don't think it's the IP though. I know that CloudFlare will block for all sorts of reasons. Lack of a User-Agent string is just one. I suspect urllib could be configured to be acceptable, but it's hard to know exactly what CloudFlare doesn't like about it.

**Comment by Teuns** [comment]
I've just pushed some commits that introduces a (WIP) request wrapper that revolves around `urllib` and replaced all `requests` with it. I successfully authenticated and downloaded an ebook with it using a VPN. The code obviously needs to be refacatored and tested properly but feel free to test it let me know if it works.

**Comment by rainrdx** [comment]
Thank you so much for working on this. I tried two ips, my ip on a cruise ship and another ip on azure, both shows 403 forbidden when requesting
Making request to https://authorize.kobo.com/signin?returnUrl

I feel this is more likely an ip issue with where I am. I will try again next week when I am back.

**Comment by rainrdx** [comment]
and I tried so many VPNs all failed. This is so weird. Again thank you for working on this weird issue

**Comment by bybpow** [comment]
This works for me.

**Comment by chewi** [comment]
No luck here, although the error is different.

```
Making request to https://storeapi.kobo.com/v1/initialization
Making request to https://storeapi.kobo.com/v1/library/sync
Making request to https://storeapi.kobo.com/v1/library/sync
Making request to https://storeapi.kobo.com/v1/library/sync
Skipping subscribtion entity
Skipping subscribtion entity
Downloading e0a9b304-83f1-4a7d-a170-4aee884d35c2 to /tmp/audiobooks/Adrian Tchaikovsky - Eyes of the Void e0a9b304
Making request to https://storedownloads.kobo.com/download?downloadToken=XXXXXXXX
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chewi/Projects/kobo-book-downloader/kobodl/commands/book.py", line 83, in get
    actions.GetBookOrBooks(usercls, output_dir, formatStr=format_str, productId=pid)
  File "/home/chewi/Projects/kobo-book-downloader/kobodl/actions.py", line 231, in GetBookOrBooks
    kobo.Download(bookMetadata, book_type == BookType.AUDIOBOOK, outputFilePath)
  File "/home/chewi/Projects/kobo-book-downloader/kobodl/kobo.py", line 428, in Download
    self.__DownloadAudiobook(downloadUrl, outputPath)
  File "/home/chewi/Projects/kobo-book-downloader/kobodl/kobo.py", line 347, in __DownloadAudiobook
    request = Request(url)
              ^^^^^^^^^^^^
  File "/home/chewi/Projects/kobo-book-downloader/kobodl/kobo.py", line 59, in __init__
    self.request = urllib.request.Request(url, data=data, headers=headers)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 324, in __init__
    for key, value in headers.items():
                      ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```

Admittedly I've tweaked it to use Python 3.12, 3.10 is too old for my system, but it did work fine with 3.12 before.

**Comment by Teuns** [comment]
> No luck here, although the error is different.
> 
> ```
> Making request to https://storeapi.kobo.com/v1/initialization
> Making request to https://storeapi.kobo.com/v1/library/sync
> Making request to https://storeapi.kobo.com/v1/library/sync
> Making request to https://storeapi.kobo.com/v1/library/sync
> Skipping subscribtion entity
> Skipping subscribtion entity
> Downloading e0a9b304-83f1-4a7d-a170-4aee884d35c2 to /tmp/audiobooks/Adrian Tchaikovsky - Eyes of the Void e0a9b304
> Making request to https://storedownloads.kobo.com/download?downloadToken=XXXXXXXX
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
>     return f(get_current_context().obj, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/chewi/Projects/kobo-book-downloader/kobodl/commands/book.py", line 83, in get
>     actions.GetBookOrBooks(usercls, output_dir, formatStr=format_str, productId=pid)
>   File "/home/chewi/Projects/kobo-book-downloader/kobodl/actions.py", line 231, in GetBookOrBooks
>     kobo.Download(bookMetadata, book_type == BookType.AUDIOBOOK, outputFilePath)
>   File "/home/chewi/Projects/kobo-book-downloader/kobodl/kobo.py", line 428, in Download
>     self.__DownloadAudiobook(downloadUrl, outputPath)
>   File "/home/chewi/Projects/kobo-book-downloader/kobodl/kobo.py", line 347, in __DownloadAudiobook
>     request = Request(url)
>               ^^^^^^^^^^^^
>   File "/home/chewi/Projects/kobo-book-downloader/kobodl/kobo.py", line 59, in __init__
>     self.request = urllib.request.Request(url, data=data, headers=headers)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/urllib/request.py", line 324, in __init__
>     for key, value in headers.items():
>                       ^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'items'
> ```
> 
> Admittedly I've tweaked it to use Python 3.12, 3.10 is too old for my system, but it did work fine with 3.12 before.

Seems like `urllib` doesn't like it when you pass None as the headers value (which is of course not very surprising given the fact that the type is a dictionary). My latest commit should fix it!

**Comment by chewi** [comment]
That did the trick. Many thanks.

**Comment by bybpow** [comment]
> > No luck here, although the error is different.
> > 
> > ```
> > Making request to https://storeapi.kobo.com/v1/initialization
> > Making request to https://storeapi.kobo.com/v1/library/sync
> > Making request to https://storeapi.kobo.com/v1/library/sync
> > Making request to https://storeapi.kobo.com/v1/library/sync
> > Skipping subscribtion entity
> > Skipping subscribtion entity
> > Downloading e0a9b304-83f1-4a7d-a170-4aee884d35c2 to /tmp/audiobooks/Adrian Tchaikovsky - Eyes of the Void e0a9b304
> > Making request to https://storedownloads.kobo.com/download?downloadToken=XXXXXXXX
> > Traceback (most recent call last):
> >   File "<string>", line 1, in <module>
> >   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 829, in __call__
> >     return self.main(*args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 782, in main
> >     rv = self.invoke(ctx)
> >          ^^^^^^^^^^^^^^^^
> >   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 1259, in invoke
> >     return _process_result(sub_ctx.command.invoke(sub_ctx))
> >                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 1259, in invoke
> >     return _process_result(sub_ctx.command.invoke(sub_ctx))
> >                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 1066, in invoke
> >     return ctx.invoke(self.callback, **ctx.params)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/core.py", line 610, in invoke
> >     return callback(*args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/chewi/.cache/pypoetry/virtualenvs/kobodl-NpcgVQ5e-py3.12/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
> >     return f(get_current_context().obj, *args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/chewi/Projects/kobo-book-downloader/kobodl/commands/book.py", line 83, in get
> >     actions.GetBookOrBooks(usercls, output_dir, formatStr=format_str, productId=pid)
> >   File "/home/chewi/Projects/kobo-book-downloader/kobodl/actions.py", line 231, in GetBookOrBooks
> >     kobo.Download(bookMetadata, book_type == BookType.AUDIOBOOK, outputFilePath)
> >   File "/home/chewi/Projects/kobo-book-downloader/kobodl/kobo.py", line 428, in Download
> >     self.__DownloadAudiobook(downloadUrl, outputPath)
> >   File "/home/chewi/Projects/kobo-book-downloader/kobodl/kobo.py", line 347, in __DownloadAudiobook
> >     request = Request(url)
> >               ^^^^^^^^^^^^
> >   File "/home/chewi/Projects/kobo-book-downloader/kobodl/kobo.py", line 59, in __init__
> >     self.request = urllib.request.Request(url, data=data, headers=headers)
> >                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/lib/python3.12/urllib/request.py", line 324, in __init__
> >     for key, value in headers.items():
> >                       ^^^^^^^^^^^^^
> > AttributeError: 'NoneType' object has no attribute 'items'
> > ```
> > 
> > Admittedly I've tweaked it to use Python 3.12, 3.10 is too old for my system, but it did work fine with 3.12 before.
> 
> Seems like `urllib` doesn't like it when you pass None as the headers value (which is of course not very surprising given the fact that the type is a dictionary). My latest commit should fix it!
> 
> 

This also happened to me. You also need to add the cloudscrapper patch but this fix works for the login.

**Comment by rainrdx** [comment]
I just want to share that TnS-hun's recent commits fixed the 403 problem for me
https://github.com/TnS-hun/kobo-book-downloader/commits/master/

**Comment by Teuns** [comment]
> I just want to share that TnS-hun's recent commits fixed the 403 problem for me https://github.com/TnS-hun/kobo-book-downloader/commits/master/

Interestingly enough it doesn't work for me: 

`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://authorize.kobo.com/signin (...)`

Maybe you're using it on an IP address that doesn't get blocked easily by CloudFlare? It used to work weeks before though.

**Comment by rainrdx** [comment]
> > I just want to share that TnS-hun's recent commits fixed the 403 problem for me https://github.com/TnS-hun/kobo-book-downloader/commits/master/
> 
> Interestingly enough it doesn't work for me:
> 
> `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://authorize.kobo.com/signin (...)`
> 
> Maybe you're using it on an IP address that doesn't get blocked easily by CloudFlare? It used to work weeks before though.

That's really weird. I think I will just stop here as it's really hard to debug this. Cloudflare is just flaky to bypass and I got my tokens. Thank you!

**Comment by rainrdx** [comment]
Just came back home and with clean ip, everything works with your commits. I guess this was just an ip issue with cloudflare. Thank you!

**Comment by rainrdx** [comment]
sadly, seems nothing works for me now. My home IP, my office IP, etc. all show up with the 403 forbidden for authorize.kobo.com sigh....

**Comment by nigeldixon** [comment]
works here!

**Comment by Renari** [comment]
This branch also worked for me after getting 403 errors.

**Comment by linyaa-kiwi** [comment]
I submitted MR https://github.com/subdavis/kobo-book-downloader/pull/134 that fixes the issue for me.

It's a clean MR that does only one thing: change the HTTP headers. It does not replace `requests` with `urllib`, or do any other invasive changes.

**Comment by Teuns** [comment]
> I submitted MR #134 that fixes the issue for me.
> 
> It's a clean MR that does only one thing: change the HTTP headers. It does not replace `requests` with `urllib`, or do any other invasive changes.

That's probably better indeed, altough it doesn't fix it for everyone (including me). Bypassing CloudFlare is just very tricky, sometimes a simple header change does the trick, sometimes you need to change the way requests are being sent (like here). I'm inclined to close this one, unless someone is willing to review it, since it's not in very good state at the moment.

**Comment by mpross512** [comment]
I found [this commit](https://github.com/TnS-hun/kobo-book-downloader/commit/04d8c42d97661bd580fbfe62d681c5be86edd1c4) from @TnS-hun that uses the web login that the kobo ereaders use. Maybe someone could take a crack at implementing this in this branch!

**Comment by subdavis** [comment]
I tested and this isn't working for me either.  Still getting 403.

Instead, I'm going to go with #137 which is a nicer solution that will work for more people.  Thank you for the effort!
